services:

  broker1:
    build: .
    container_name: broker1
    ports:
      - "8081:8080"
    environment:
      - BROKER_ID=broker1
      - PEER=ws://broker2:8080/federation
    networks:
      - brokers-net
    depends_on:
      - broker2

  broker2:
    build: .
    container_name: broker2
    ports:
      - "8082:8080"
    environment:
      - BROKER_ID=broker2
      - PEER=ws://broker3:8080/federation
    networks:
      - brokers-net
    depends_on:
      - broker3

  broker3:
    build: .
    container_name: broker3
    ports:
      - "8083:8080"
    environment:
      - BROKER_ID=broker3
      - PEER=ws://broker1:8080/federation
    networks:
      - brokers-net

networks:
  brokers-net:
    driver: bridge